name: SSE CI/CD

on: [push]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install clang-format"
        run: sudo apt-get update -y && sudo apt-get install -y clang-format
      - name: "run style check"
        run: clang-format -Werror src/*
  
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: "install dependecies"
          run: sudo apt-get update -y && sudo apt-get install -y cmake build-essential
        - name: "install further dependencies"
          run: sudo apt-get install libboost-test-dev libeigen3-dev
        - name: "create build directory"
          run: mkdir build && cd build
        - name: "cmake"
          run: cmake ..
        - name: "make"
          run: make -j

  test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: "install dependecies"
          run: sudo apt-get update -y && sudo apt-get install -y cmake build-essential
        - name: "install further dependencies"
          run: sudo apt-get install libboost-test-dev libeigen3-dev
        - name: "create build directory"
          run: mkdir build && cd build
        - name: "cmake"
          run: cmake ..
        - name: "make"
          run: make -j
        - name: "run tests"
          run: make test

